---
title: "Check u(x,t=1)"
author: "Isabel Kim"
date: "4/29/2022"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load in the dataset and filter to get only the N=30,000 runs

* a = 0.02
* sigma = 0.01
* uhat = 40%
* b = 1
* k = 0.2
```{r}
library(tidyverse)
data = read_csv("/Users/isabelkim/Desktop/year2/underdominance/reaction-diffusion/bistable-R-waves/xpoints.csv") %>% filter(N==30000)

# 41 replicates

# x1 = 0.47
avg_x1 = data %>% .$`x=0.47_freq` %>% mean()

# x2 = 0.5
avg_x2 = data %>% .$`x=0.5_freq` %>% mean()

# x = 0.54
avg_x3 = data %>% .$`x=0.54_freq` %>% mean()


predicted_x1 = 0.05098523
predicted_x2 = 0.6537119
predicted_x3 = 0.01833609

print(paste("Predicted u(-0.03,t=1) = ", round(predicted_x1,4), " vs observed = ",round(avg_x1,4)))

print(paste("Predicted u(0.0,t=1) = ", round(predicted_x2,4), " vs observed = ",round(avg_x2,4)))

print(paste("Predicted u(0.04,t=1) = ", round(predicted_x3,4), " vs observed = ",round(avg_x3,4)))
```

Observed rates are a *bit* lower than the predicted ones. Is diffusion too strong? Can check u'(x,t=1) next.